name: Linter
on: [pull_request]
jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.GH_PAT_TOKEN }}
          reporter: github-pr-review
          level: error
          fail_on_error: true
          checkstyle_config: ./properties_file/test_checks.xml
          properties_file: ./properties_file/additional.properties